services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Fixed port mapping for local development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # Kamiwaza integration
      KAMIWAZA_ENDPOINT: ${KAMIWAZA_ENDPOINT:-http://host.docker.internal:7777/api/}
      KAMIWAZA_VERIFY_SSL: ${KAMIWAZA_VERIFY_SSL:-false}
      KAMIWAZA_API_URI: ${KAMIWAZA_API_URI:-https://host.docker.internal/api}
      KAMIWAZA_FORCE_HTTP: ${KAMIWAZA_FORCE_HTTP:-true}
      NODE_TLS_REJECT_UNAUTHORIZED: ${NODE_TLS_REJECT_UNAUTHORIZED:-0}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"  # Map to port 3001 to avoid conflicts
    depends_on:
      backend:
        condition: service_healthy
    environment:
      # Backend URL for the API proxy
      BACKEND_URL: http://backend:8000
      NODE_TLS_REJECT_UNAUTHORIZED: ${NODE_TLS_REJECT_UNAUTHORIZED:-0}

networks:
  default:
    name: app_garden_template_local_network