import type { Metadata } from "next";
import { Montserrat, Nunito } from "next/font/google";
import "./globals.css";
import "../styles/theme.css";
import "../styles/kamiwaza.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <script dangerouslySetInnerHTML={{
          __html: `
            // Hide React DevTools
            if (typeof window !== 'undefined' && window.__REACT_DEVTOOLS_GLOBAL_HOOK__) {
              window.__REACT_DEVTOOLS_GLOBAL_HOOK__.inject = function() {};
            }
          `
        }} />
      </head>
      <body
        className={`${montserrat.variable} ${nunito.variable} antialiased`}
        style={{
          fontFamily: "'Montserrat', 'Nunito', 'Segoe UI', 'Inter', 'Arial', 'sans-serif'"
        }}
      >
        {children}
      </body>
    </html>
  );
}
